import React, { useState, useEffect } from 'react';
import { 
  Library as LibraryIcon, Search, Eye, RefreshCw, 
  Trash2, TrendingUp, AlertCircle, Calendar, 
  ChevronRight, Sparkles, Filter
} from 'lucide-react';
import dataService from '../../services/dataService';

const Library = () => {
  const [insights, setInsights] = useState([]);
  const [loading, setLoading]  = useState(true);
  const [filter, setFilter]    = useState('All');

  useEffect(() => {
    const fetchInsights = async () => {
      setLoading(true);
      try {
        const data = await dataService.getLibraryData();
        setInsights(data || []);
      } catch (err) {
        console.error("Library sync failure:", err);
      } finally {
        setLoading(false);
      }
    };
    fetchInsights();
  }, []);

  const categories = ['All', 'Growth', 'Anomaly', 'Trend', 'Model'];

  const filtered = insights.filter(item => 
    filter === 'All' || item.category === filter
  );

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '32px' }}>
      
      {/* ── Page Header ── */}
      <div className="surface glass" style={{ padding: '24px 32px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
           <nav style={{ fontSize: '11px', textTransform: 'uppercase', color: 'var(--text-secondary)', letterSpacing: '0.1em', marginBottom: '8px' }}>Store / Insights Archive</nav>
           <h1 className="outfit" style={{ fontSize: '28px', marginBottom: '4px' }}>Insights Library</h1>
           <p style={{ color: 'var(--text-secondary)', fontSize: '14px' }}>Historically preserved business observations generated by the AI Analyst.</p>
        </div>
        
        <div style={{ display: 'flex', gap: '12px' }}>
           <div style={{ position: 'relative' }}>
              <Search size={18} color="var(--text-secondary)" style={{ position: 'absolute', left: '16px', top: '50%', transform: 'translateY(-50%)' }} />
              <input 
                 type="text" 
                 placeholder="Search insights..." 
                 style={{ padding: '10px 16px 10px 48px', background: 'var(--bg-color)', border: '1px solid var(--border-color)', borderRadius: '12px', color: 'var(--text-primary)', outline: 'none', width: '280px' }}
              />
           </div>
           <button className="btn btn-primary" style={{ display: 'flex', gap: '8px' }} onClick={() => setLoading(true)}>
             <RefreshCw size={18} className={loading ? 'spin' : ''} /> Synchronize
           </button>
        </div>
      </div>

      {/* ── Filters ── */}
      <div style={{ display: 'flex', gap: '8px' }}>
         {categories.map(cat => (
           <button
              key={cat}
              onClick={() => setFilter(cat)}
              style={{
                padding: '8px 20px', borderRadius: '12px', fontSize: '13px', cursor: 'pointer', border: 'none',
                background: filter === cat ? 'var(--accent-color)' : 'var(--surface-color)',
                color: filter === cat ? '#000' : 'var(--text-secondary)',
                fontWeight: filter === cat ? 'bold' : 'normal',
                transition: 'all 0.2s', border: filter === cat ? 'none' : '1px solid var(--border-color)'
              }}
           >{cat}</button>
         ))}
      </div>

      {loading && (
        <div style={{ padding: '80px', textAlign: 'center' }}>
           <RefreshCw size={40} className="spin" style={{ margin: '0 auto 16px', color: 'var(--accent-color)' }} />
           <p className="outfit">Reconstructing insight ledger...</p>
        </div>
      )}

      {!loading && filtered.length === 0 && (
         <div className="surface" style={{ padding: '60px', textAlign: 'center', opacity: 0.5 }}>
            <LibraryIcon size={48} style={{ margin: '0 auto 16px' }} />
            <p>No archived insights found in the current store.</p>
         </div>
      )}

      {/* ── Insights Grid ── */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(420px, 1fr))', gap: '24px' }}>
        {filtered.map(item => (
          <div key={item.id} className="surface" style={{ padding: '32px', display: 'flex', flexDirection: 'column', gap: '24px', transition: 'transform 0.2s' }} onMouseOver={e => e.currentTarget.style.transform = 'translateY(-4px)'} onMouseOut={e => e.currentTarget.style.transform = 'translateY(0)'}>
            
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
               <div style={{ display: 'flex', gap: '16px', alignItems: 'center' }}>
                  <div style={{ width: '40px', height: '40px', borderRadius: '10px', display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'var(--bg-color)', border: '1px solid var(--border-color)' }}>
                     {item.category === 'Growth' && <TrendingUp size={20} color="var(--accent-color)" />}
                     {item.category === 'Anomaly' && <AlertCircle size={20} color="#ef4444" />}
                     {item.category === 'Trend' && <Sparkles size={20} color="#a855f7" />}
                  </div>
                  <div>
                     <h3 className="outfit" style={{ fontSize: '18px' }}>{item.title}</h3>
                     <div style={{ fontSize: '11px', color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: '0.05em', marginTop: '2px' }}>{item.category} • Recorded {item.time}</div>
                  </div>
               </div>
               <div style={{ padding: '4px 10px', borderRadius: '20px', background: 'var(--surface-hover)', fontSize: '10px', fontWeight: 'bold', color: 'var(--accent-color)', textTransform: 'uppercase' }}>
                  {item.impact} IMPACT
               </div>
            </div>

            <p style={{ fontSize: '14px', color: 'var(--text-secondary)', lineHeight: '1.6' }}>{item.description}</p>

            <div style={{ display: 'flex', gap: '10px', marginTop: 'auto', borderTop: '1px solid var(--border-color)', paddingTop: '20px' }}>
               <button className="btn btn-ghost" style={{ flex: 1, border: '1px solid var(--border-color)', display: 'flex', gap: '8px', justifyContent: 'center' }}>
                  <Eye size={16} /> Open Insight
               </button>
               <button className="btn btn-ghost" style={{ padding: '8px', color: '#ef4444' }}>
                  <Trash2 size={18} />
               </button>
            </div>
          </div>
        ))}
      </div>

      <style>{`
        .spin { animation: spin 1s linear infinite; }
        @keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
      `}</style>
    </div>
  );
};

export default Library;
