"""
Unit tests for the Excel import service.

Tests parsing, validation, and insertion logic of the excel_importer module.
Uses a real temporary Excel file generated by pandas to simulate uploads.
"""

import os
import tempfile
from pathlib import Path
from unittest.mock import MagicMock, patch

import pandas as pd
import pytest

from serving.services.excel_importer import (
    import_products_from_excel,
    import_orders_from_excel,
    generate_products_template,
    generate_orders_template,
    _is_empty,
    _validate_columns,
    _find_or_create_category,
    PRODUCTS_EXPECTED_COLUMNS,
    ORDERS_EXPECTED_COLUMNS,
)


# ─── Fixtures ─────────────────────────────────────────────────────────────

@pytest.fixture
def mock_repo():
    """Mocked repository returning empty results for all lookups."""
    repo = MagicMock()

    # Products table: return empty for sku lookups
    def get_record_side_effect(table_name, filters=None, columns=None):
        if table_name == "products":
            if filters and filters.get("sku_code"):
                return []  # no existing product
            return []  # no products at all
        if table_name == "categories":
            if filters and filters.get("name"):
                return []  # no existing category
            return []
        if table_name == "customers":
            if filters and filters.get("email"):
                return []
            if filters and filters.get("name"):
                return []
            return []
        return []

    repo.get_record.side_effect = get_record_side_effect
    repo.add_record.return_value = True
    repo.update_record.return_value = True
    repo.is_connected.return_value = True
    return repo


@pytest.fixture
def products_excel_path():
    """Create a temporary Excel file with valid product data."""
    df = pd.DataFrame({
        "sku_code": ["SKU-TEST-001", "SKU-TEST-002", "SKU-TEST-003"],
        "name": ["Test Product A", "Test Product B", "Test Product C"],
        "base_price": [19.99, 29.99, 39.99],
        "unit_cost": [10.00, 15.00, 20.00],
        "current_stock": [100, 50, 200],
        "safety_stock": [20, 10, 40],
        "status": ["active", "active", "active"],
        "category_name": ["Test Category", "Test Category", "Another Category"],
        "weight": [1.0, 2.5, 0.5],
    })
    path = os.path.join(tempfile.gettempdir(), "test_products.xlsx")
    df.to_excel(path, index=False, engine="openpyxl")
    yield path
    try:
        os.remove(path)
    except OSError:
        pass


@pytest.fixture
def orders_excel_path():
    """Create a temporary Excel file with valid order data."""
    df = pd.DataFrame({
        "order_id": ["ORD-TEST-001", "ORD-TEST-001", "ORD-TEST-002"],
        "order_date": ["2026-06-01", "2026-06-01", "2026-06-02"],
        "customer_name": ["Test Corp", "Test Corp", "Another Inc"],
        "customer_email": ["test@corp.com", "test@corp.com", "info@another.com"],
        "product_sku": ["SKU-TEST-001", "SKU-TEST-002", "SKU-TEST-001"],
        "quantity": [10, 5, 3],
        "price_at_sale": [19.99, 29.99, 19.99],
        "status": ["completed", "completed", "pending"],
        "total_amount": [349.85, 349.85, 59.97],
    })
    path = os.path.join(tempfile.gettempdir(), "test_orders.xlsx")
    df.to_excel(path, index=False, engine="openpyxl")
    yield path
    try:
        os.remove(path)
    except OSError:
        pass


# ─── Tests: Validation ────────────────────────────────────────────────────

def test_validate_columns_all_present():
    """Required columns exist."""
    df = pd.DataFrame({"sku_code": [1], "name": ["A"]})
    missing = _validate_columns(df, PRODUCTS_EXPECTED_COLUMNS)
    assert missing == []


def test_validate_columns_missing():
    """A required column is missing."""
    df = pd.DataFrame({"name": ["A"]})
    missing = _validate_columns(df, PRODUCTS_EXPECTED_COLUMNS)
    assert "sku_code" in missing


def test_validate_columns_case_insensitive():
    """Column name matching is case-insensitive."""
    df = pd.DataFrame({"SKU_CODE": [1], "Name": ["A"]})
    missing = _validate_columns(df, PRODUCTS_EXPECTED_COLUMNS)
    assert missing == []


# ─── Tests: _is_empty ─────────────────────────────────────────────────────

def test_is_empty_none():
    assert _is_empty(None) is True


def test_is_empty_nan():
    import numpy as np
    assert _is_empty(np.nan) is True


def test_is_empty_empty_string():
    assert _is_empty("") is True


def test_is_empty_valid_string():
    assert _is_empty("hello") is False


def test_is_empty_zero():
    assert _is_empty(0) is False


# ─── Tests: Category Lookup ───────────────────────────────────────────────

def test_find_or_create_category_exists(mock_repo):
    """Category already exists — should return its ID."""
    # Override the side_effect from fixture with a fixed return
    mock_repo.get_record.side_effect = None
    mock_repo.get_record.return_value = [{"id": 5}]
    cat_id = _find_or_create_category("Electronics", mock_repo)
    assert cat_id == 5
    # Should not have tried to insert
    mock_repo.add_record.assert_not_called()


def test_find_or_create_category_creates_new(mock_repo):
    """Category doesn't exist — should create and return new ID."""
    # First call returns empty, second returns the newly created record
    mock_repo.get_record.side_effect = [[], [{"id": 10}]]
    cat_id = _find_or_create_category("New Category", mock_repo)
    assert cat_id == 10
    mock_repo.add_record.assert_called_once_with("categories", {"name": "New Category"})


# ─── Tests: Import Products ───────────────────────────────────────────────

@patch("serving.services.excel_importer.get_repository")
def test_import_products_success(mock_get_repo, products_excel_path, mock_repo):
    """All valid rows should be imported successfully."""
    mock_get_repo.return_value = mock_repo
    result = import_products_from_excel(products_excel_path)

    assert result["status"] == "completed"
    assert result["total_rows"] == 3
    assert result["rows_imported"] == 3
    assert result["rows_failed"] == 0
    assert result["rows_skipped"] == 0


@patch("serving.services.excel_importer.get_repository")
def test_import_products_empty_sku_skipped(mock_get_repo, mock_repo):
    """Rows with empty sku_code should be skipped."""
    df = pd.DataFrame({
        "sku_code": ["", None, "SKU-VALID"],
        "name": ["No SKU", "Also no SKU", "Valid"],
    })
    path = os.path.join(tempfile.gettempdir(), "test_products_skipped.xlsx")
    df.to_excel(path, index=False, engine="openpyxl")

    mock_get_repo.return_value = mock_repo
    result = import_products_from_excel(path)
    try:
        os.remove(path)
    except OSError:
        pass

    assert result["status"] == "completed"
    assert result["total_rows"] == 3
    assert result["rows_skipped"] == 2  # two empty sku_code rows
    assert result["rows_imported"] == 1


@patch("serving.services.excel_importer.get_repository")
def test_import_products_missing_required_column(mock_get_repo):
    """Missing required column should return an error."""
    df = pd.DataFrame({"name": ["Product A"]})  # missing sku_code
    path = os.path.join(tempfile.gettempdir(), "test_products_missing_col.xlsx")
    df.to_excel(path, index=False, engine="openpyxl")

    mock_get_repo.return_value = MagicMock()
    result = import_products_from_excel(path)
    try:
        os.remove(path)
    except OSError:
        pass

    assert result["status"] == "error"
    assert "sku_code" in result.get("message", "")


# ─── Tests: Import Orders ─────────────────────────────────────────────────

@patch("serving.services.excel_importer.get_repository")
def test_import_orders_success(mock_get_repo, orders_excel_path, mock_repo):
    """Valid order rows should create orders and sales records."""
    # Mock product lookup to return existing products
    def get_record_with_products(table_name, filters=None, columns=None):
        if table_name == "products":
            sku = filters.get("sku_code") if filters else None
            if sku == "SKU-TEST-001":
                return [{"id": 1}]
            if sku == "SKU-TEST-002":
                return [{"id": 2}]
            if sku == "SKU-TEST-003":
                return [{"id": 3}]
            return [{"id": 1}]
        if table_name == "categories" and filters and filters.get("name"):
            return []
        if table_name == "customers":
            return []
        if table_name == "orders":
            return []
        return []

    mock_repo.get_record.side_effect = get_record_with_products
    mock_repo.add_record.return_value = True
    mock_get_repo.return_value = mock_repo

    result = import_orders_from_excel(orders_excel_path)

    assert result["status"] == "completed"
    assert result["total_rows"] == 3
    # 3 line items: ORD-001 has 2 items, ORD-002 has 1
    assert result["rows_imported"] == 3
    assert result["rows_failed"] == 0


@patch("serving.services.excel_importer.get_repository")
def test_import_orders_unknown_sku(mock_get_repo, mock_repo):
    """Rows referencing non-existing product skus should fail."""
    df = pd.DataFrame({
        "order_id": ["ORD-FAIL"],
        "order_date": ["2026-06-01"],
        "product_sku": ["NONEXISTENT-SKU"],
        "quantity": [1],
        "price_at_sale": [10.0],
    })
    path = os.path.join(tempfile.gettempdir(), "test_orders_fail.xlsx")
    df.to_excel(path, index=False, engine="openpyxl")

    # Mock product lookup to return empty for any SKU
    mock_repo.get_record.return_value = []  # no products found
    mock_get_repo.return_value = mock_repo

    result = import_orders_from_excel(path)
    try:
        os.remove(path)
    except OSError:
        pass

    assert result["status"] == "completed"
    assert result["rows_failed"] == 1  # the one row that tried to look up SKU


# ─── Tests: Template Generation ───────────────────────────────────────────

def test_generate_products_template_creates_file():
    """Template generator should create a valid .xlsx file."""
    path = generate_products_template()
    assert path is not None
    assert path.endswith(".xlsx")
    assert os.path.exists(path)

    # Read back to verify
    df = pd.read_excel(path, engine="openpyxl")
    assert "sku_code" in df.columns
    assert "name" in df.columns
    assert len(df) > 0  # has sample rows
    try:
        os.remove(path)
    except OSError:
        pass


def test_generate_orders_template_creates_file():
    """Order template generator should create a valid .xlsx file."""
    path = generate_orders_template()
    assert path is not None
    assert path.endswith(".xlsx")
    assert os.path.exists(path)

    df = pd.read_excel(path, engine="openpyxl")
    assert "order_id" in df.columns
    assert "product_sku" in df.columns
    assert len(df) > 0
    try:
        os.remove(path)
    except OSError:
        pass
